// Package reporter provides a Golang interface for parsing JSON generated by Reporter (http://reporter-app.com).
// It has built in support for getting the JSON from the local filesystem, a string, or even Dropbox.
// Most of the work is based on experimentation and the schema guide found at https://gist.github.com/dbreunig/9315705.
//
// Many comments in the code come directly from the schema gist
package reporter

import (
	"encoding/json"
	"time"
)

// SchemaVersion stores the schema version for the day that is currently being processed.
var SchemaVersion = 2 // Schema version 1 used Apple epoch timestamps and no ID's for objects.

// File contains information about the JSON source file
type File struct {
	Name             string    `json:"name,omitempty"`
	Path             string    `json:"path,omitempty"`
	Source           string    `json:"source,omitempty"`
	ModifiedTime     time.Time `json:"modifiedTime,omitempty"`
	TimeFromFilename time.Time `json:"timeFromFilename,omitempty"`
	Contents         string    `json:"contents,omitempty"`
}

// A Backend is a source for Reports.
// To implement a new backend, you need only implement these four functions.
// For end-user conveinence you should also implement a New<Backend>Backend function
// i.e. NewDropboxBackend or NewFilesystemBackend.
type Backend interface {
	GetLatestReport() (File, error)
	GetReportForPath(string) (File, error)
	GetReportForTime(time.Time) (File, error)
	ListReports() ([]File, error)
}

// DecodeJSONString returns a Day for a raw JSON string
func DecodeJSONString(jsonString string) (Day, error) {
	var day Day
	err := json.Unmarshal([]byte(jsonString), &day)
	if err != nil {
		return day, err
	}
	day.SchemaVersion = SchemaVersion
	return day, nil
}

// DecodeFile will return a Day for a given File
func DecodeFile(file File) (Day, error) {
	var day Day
	err := json.Unmarshal([]byte(file.Contents), &day)
	if err != nil {
		return day, err
	}
	file.Contents = ""
	day.FileInfo = file
	day.Date = file.TimeFromFilename
	day.SchemaVersion = SchemaVersion
	return day, nil
}
